export const env = {
  DATABASE_URL: process.env.DATABASE_URL ?? "postgresql://chat:chat@localhost:5432/chat",
  REDIS_URL: process.env.REDIS_URL ?? "redis://localhost:6379",
  PORT: Number(process.env.API_PORT ?? 3001),
  HOST: process.env.API_HOST ?? "0.0.0.0",
  WEB_URL: process.env.WEB_URL ?? "http://localhost:3000",
  API_URL: process.env.API_URL ?? "http://localhost:3001",
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET ?? "dev-secret-change-me-32-chars-min",
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL ?? "http://localhost:3001",
  S3_ENDPOINT: process.env.S3_ENDPOINT ?? "http://localhost:9000",
  S3_REGION: process.env.S3_REGION ?? "us-east-1",
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID ?? "minioadmin",
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY ?? "minioadmin123",
  S3_BUCKET: process.env.S3_BUCKET ?? "chat-attachments",
  S3_FORCE_PATH_STYLE: (process.env.S3_FORCE_PATH_STYLE ?? "true") === "true",
  MAIL_HOST: process.env.MAIL_HOST ?? "localhost",
  MAIL_PORT: Number(process.env.MAIL_PORT ?? 1025),
  MAIL_FROM: process.env.MAIL_FROM ?? "Pulse <noreply@pulse.local>",
};
